project:
  type: website

website:
  title: "Research Proposal"
  search: false
  navbar:
    left:
      - href: about.qmd
        text: "About it"
      - href: references.qmd
        text: "References"

    right: 
      - icon: person-lines-fill
        aria-label: website
        href: https://gregmaya.github.io/personal_web/
      - icon: envelope
        aria-label: email
        href: "mailto:gregoriomaya@gmail.com" 
  

  page-footer:
      center: "© Copyright 2024 Greg Maya."


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
