project:
  type: website

website:
  favicon: assets/favicon.png
  title: "Research Proposal"
  search: false
  navbar:
    left:
      - href: about.qmd
        text: "About it"
      - text: "References"
        menu: 
        - href: initiatives.qmd
          text : "Initiatives"
        - href: bibliography.qmd
          text : "Bibliography"


    right: 
      - icon: person-lines-fill
        aria-label: website
        href: https://gregmaya.github.io/personal_web/
      - icon: envelope
        aria-label: email
        href: "mailto:gregoriomaya@gmail.com" 
  

  page-footer:
      center: "© Copyright 2025 Greg Maya."


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
