project:
  type: website
  output-dir: _site  # Make sure this is correctly set

website:
  favicon: assets/favicon.png
  title: "Research Proposal"
  google-analytics: G-4C6QQ0DV05 #my google tag
  cookie-consent: false
  search: false
  back-to-top-navigation: true 
  sidebar: 
    - id: application
      style: "docked"
      contents: 
        - href: application/index.qmd
        - href: application/thematization.qmd
        - href: application/project_description.qmd
        - href: application/state_of_the_art.qmd
  
  navbar:
    left:
      - text: "Slide Deck"
        href: abstract/cities4health.qmd
      - href: abstract/application_prep.qmd
      - text: "References"
        menu: 
        - href: initiatives.qmd
          text : "Initiatives"
        - href: bibliography.qmd
          text : "Bibliography"


    right: 
      - icon: person-lines-fill
        aria-label: website
        href: https://gregmaya.github.io/personal_web/
      - icon: envelope
        aria-label: email
        href: "mailto:gregoriomaya@gmail.com" 
  

  page-footer:
      center: "© Copyright 2025 Greg Maya."


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    include-in-header: gtm_code_head.html
    include-before-body: gtm_code_body.html

