---
title: Ignore
---
# The logistics

## What is an Industry PhD ?

## The Programme Framework 
[Danish Innovation Fund: Industrial Researcher] (https://innovationsfonden.dk/en/p/industrial-researcher#apply_options296) 
### Main Points
- Time: 3 year funded program
- Funding limits: ...
- Research location: ...
___

### Important deadlines


## The Research topic 

* more on this under [The Topic section](#the-topic) 

## The Parties 
- The researcher : **Me!**
- Industry Partner(s) : **Ramboll** (Danish HQ) + Potentially other from health industry.
- Accademic partner: _TBC_
  - Candidates : 
    - [Dr. Jens Kandt, CASA - UCL](https://profiles.ucl.ac.uk/37018)
    - [Dr. Robert Hughes, The London School of Hygiene & Tropical Medicine](https://www.lshtm.ac.uk/aboutus/people/hughes.robert)


# The Topic
- The challenges of implementing Health outcomes as drivers of Urban Development.

## Context 
### Frameworks
- SDGs (list the relevant ones for Healthy cities)
- _(other relevant urban policies)_
____

### The problem(s)
- **Narrative mismatch** : given that this is at the edge of two disciplines
- **Untracked urban development** : traditionally urban development has not been implemented with a rigourous methodology for tracking its actions over time.
- **Lack of technical skill**: Urbanists tend not to be trained in techniques for 

## Literature Review
_Some few parragraphs summarising what papers say about this topic_

* visit a broader list under the [Bibliogrphy tab](../bibliography.qmd)

## The case studies 
_TBC_ 

> This is something that can be further refined according to partners' current cases.

## The research goals
- create links between the policies and the possible tangible actions on the cities that impact health.
- calculate the economic argument that could untangle the incentives for pursuing an urban development path driven by saving in long term public health systems.
- initiate a commercially viable framework for approaching opportunities for urban redevelopment.
- _(potentially some more)_