name: Quarto Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # Optional: Retry setup in case of network failure
        continue-on-error: true

      - name: Install Quarto manually if setup fails
        if: failure()
        run: |
          curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb
          sudo dpkg -i quarto-linux-amd64.deb

      - name: Render site
        run: quarto render

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
          artifact_name: site-artifact

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: site-artifact
